DELETE FROM app.view;
DELETE FROM app.status;
DELETE FROM app.credit;
DELETE FROM app.episode;
DELETE FROM app.own;
DELETE FROM app.role;
DELETE FROM app.person;
DELETE FROM app.user;
DELETE FROM app.series_season;
DELETE FROM app.synopsis;
ALTER TABLE app.synopsis AUTO_INCREMENT = 1;
INSERT INTO app.synopsis VALUES (NULL,'Events');
INSERT INTO app.synopsis VALUES (NULL,'Stuff happens');
INSERT INTO app.synopsis VALUES (NULL,'They do things');
INSERT INTO app.synopsis VALUES (NULL,'A guy does a thing');
INSERT INTO app.synopsis VALUES (NULL,'No one does anything');
ALTER TABLE app.user AUTO_INCREMENT = 1;
INSERT INTO app.user VALUES (NULL,'First1','Last1','fl1@test.com','fl1','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First2','Last2','fl2@test.com','fl2','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First3','Last3','fl3@test.com','fl3','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First4','Last4','fl4@test.com','fl4','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First5','Last5','fl5@test.com','fl5','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First6','Last6','fl6@test.com','fl6','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First7','Last7','fl7@test.com','fl7','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First8','Last8','fl8@test.com','fl8','password','user',NOW(),NULL,NULL,1);
INSERT INTO app.user VALUES (NULL,'First9','Last9','fl9@test.com','fl9','password','user',NOW(),NULL,NULL,1);
ALTER TABLE app.person AUTO_INCREMENT = 1;
INSERT INTO app.person VALUES (NULL,'Alice','Anderson');
INSERT INTO app.person VALUES (NULL,'Bob','Burns');
INSERT INTO app.person VALUES (NULL,'Cal','Cudda');
INSERT INTO app.person VALUES (NULL,'Dave','Davis');
ALTER TABLE app.role AUTO_INCREMENT = 1;
INSERT INTO app.role VALUES (NULL,'Director');
INSERT INTO app.role VALUES (NULL,'Writer');
INSERT INTO app.role VALUES (NULL,'Producer');
INSERT INTO app.role VALUES (NULL,'Star');
ALTER TABLE app.series_season AUTO_INCREMENT = 1;
INSERT INTO app.series_season VALUES (NULL,'TOS',1);
INSERT INTO app.series_season VALUES (NULL,'TOS',2);
INSERT INTO app.series_season VALUES (NULL,'TOS',3);
INSERT INTO app.series_season VALUES (NULL,'TNG',1);
ALTER TABLE app.episode AUTO_INCREMENT = 1;
INSERT INTO app.episode VALUES (NULL,'Episode 1',1,1);
INSERT INTO app.episode VALUES (NULL,'Episode 2',2,1);
INSERT INTO app.episode VALUES (NULL,'Episode 4',3,2);
INSERT INTO app.episode VALUES (NULL,'Episode 5',4,2);
INSERT INTO app.episode VALUES (NULL,'Episode 8',5,3);
ALTER TABLE app.credit AUTO_INCREMENT = 1;
INSERT INTO app.credit VALUES (NULL,1,1,1);
INSERT INTO app.credit VALUES (NULL,2,1,2);
INSERT INTO app.credit VALUES (NULL,3,1,2);
INSERT INTO app.credit VALUES (NULL,4,1,1);
INSERT INTO app.credit VALUES (NULL,1,2,2);
INSERT INTO app.credit VALUES (NULL,1,3,1);
ALTER TABLE app.own AUTO_INCREMENT = 1;
INSERT INTO app.own VALUES (NULL,8,1);
INSERT INTO app.own VALUES (NULL,8,2);
INSERT INTO app.own VALUES (NULL,8,3);
INSERT INTO app.own VALUES (NULL,8,4);
INSERT INTO app.own VALUES (NULL,9,1);
ALTER TABLE app.status AUTO_INCREMENT = 1;
INSERT INTO app.status VALUES (NULL,'Unwatched');
INSERT INTO app.status VALUES (NULL,'Queued');
INSERT INTO app.status VALUES (NULL,'In Progress');
INSERT INTO app.status VALUES (NULL,'Finished');
ALTER TABLE app.view AUTO_INCREMENT = 1;
INSERT INTO app.view VALUES (NULL,1,1,1);
INSERT INTO app.view VALUES (NULL,1,1,2);
INSERT INTO app.view VALUES (NULL,1,3,3);
INSERT INTO app.view VALUES (NULL,1,1,4);
INSERT INTO app.view VALUES (NULL,1,4,5);