ALTER TABLE series_season DISABLE KEYS;
SET foreign_key_checks = 0;
TRUNCATE TABLE series_season;
INSERT INTO series_season (series_name, season) VALUES ('First',1);
INSERT INTO series_season (series_name, season) VALUES ('First',2);
INSERT INTO series_season (series_name, season) VALUES ('First',3);
INSERT INTO series_season (series_name, season) VALUES ('First',4);
INSERT INTO series_season (series_name, season) VALUES ('Second',1);
INSERT INTO series_season (series_name, season) VALUES ('Third',1);
INSERT INTO series_season (series_name, season) VALUES ('Third',2);
INSERT INTO series_season (series_name, season) VALUES ('Third',3);
INSERT INTO series_season (series_name, season) VALUES ('Third',4);
INSERT INTO series_season (series_name, season) VALUES ('Third',5);
SET foreign_key_checks = 1;
ALTER TABLE series_season ENABLE KEYS;