ALTER TABLE episode DISABLE KEYS;
SET foreign_key_checks = 0;
TRUNCATE TABLE episode;
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 1',1);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 2',1);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 3',1);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 4',1);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 1',2);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 2',2);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 3',2);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 4',2);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 1',3);
INSERT INTO episode (ep_title, series_season_id) VALUES ('Episode 2',3);
SET foreign_key_checks = 1;
ALTER TABLE episode ENABLE KEYS;