ALTER TABLE user DISABLE KEYS;
SET foreign_key_checks = 0;
TRUNCATE TABLE user;
INSERT INTO user (first_name, last_name, email, user_name, password, privileges) VALUES ("First1","Last1","fl1@test.com","fl1","password","user");
INSERT INTO user (first_name, last_name, email, user_name, password, privileges) VALUES ("First2","Last2","fl2@test.com","fl2","password","user");
INSERT INTO user (first_name, last_name, email, user_name, password, privileges) VALUES ("First3","Last3","fl3@test.com","fl3","password","user");
INSERT INTO user (first_name, last_name, email, user_name, password, privileges) VALUES ("First4","Last4","fl4@test.com","fl4","password","user");
INSERT INTO user (first_name, last_name, email, user_name, password, privileges) VALUES ("First5","Last5","fl5@test.com","fl5","password","user");
INSERT INTO user (first_name, last_name, email, user_name, password, privileges) VALUES ("First6","Last6","fl6@test.com","fl6","password","user");
SET foreign_key_checks = 1;
ALTER TABLE user ENABLE KEYS;
