ALTER TABLE role DISABLE KEYS;
SET foreign_key_checks = 0;
TRUNCATE TABLE role;
INSERT INTO role (role_name) VALUES ('Director');
INSERT INTO role (role_name) VALUES ('Producer');
INSERT INTO role (role_name) VALUES ('Starring');
INSERT INTO role (role_name) VALUES ('Guest Star');
INSERT INTO role (role_name) VALUES ('Featuring');
INSERT INTO role (role_name) VALUES ('Writer');
INSERT INTO role (role_name) VALUES ('Editor');
INSERT INTO role (role_name) VALUES ('Clown');
SET foreign_key_checks = 1;
ALTER TABLE role ENABLE KEYS;